version: "3.1"

services:
  db:
    container_name: fin-postgres
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#    ports:
#      - 5432:5432
    restart: always
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data

  backend:
    container_name: fin-backend
    build: .
    command: python3 manage.py runserver localhost
    environment:
      - ENV_DEBUG=True
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - db
