# Generated by Django 5.0 on 2023-12-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinNadzor', '0002_financialorganization_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinNadzor.executive')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinNadzor.financialorganization')),
            ],
            options={
                'unique_together': {('executive', 'organization', 'start_date', 'end_date')},
            },
        ),
        migrations.AddField(
            model_name='executive',
            name='employments',
            field=models.ManyToManyField(through='FinNadzor.Employment', to='FinNadzor.financialorganization'),
        ),
    ]
