# Generated by Django 5.0 on 2023-12-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinNadzor', '0003_employment_executive_employments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='full_name',
        ),
    ]
