# Generated by Django 5.0 on 2023-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinNadzor', '0004_remove_executive_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
    ]
