# Generated by Django 5.0 on 2023-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinNadzor', '0005_executive_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='financial_organization_images/'),
        ),
    ]
